version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: provider_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - ./backend/.env.example
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/provider_catalog
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://backend:8000
    ports:
      - "5173:80"

volumes:
  db-data:
